---
- name: "Installing required packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    update_cache: true
    upgrade: "safe"
    packages:
      - {name: "keepalived"} # To enable failover between two or more servers.
      - {name: "chrony"} # The NTP server.

- name: "Setting up the Keepalived package"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/keepalived.yml"
