---
- name: "Copying the application's file to the target"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: "root"
    group: "root"
  loop:
    - {src: "homelab.conf", dest: "/etc/chrony/conf.d/"}
    - {src: "homelab.sources", dest: "/etc/chrony/sources.d/"}
  notify: "Restart Chrony"
